version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./token.json:/usr/src/app/token.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
